apiVersion: skaffold/v2beta15
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/*
build:
  local:
    push: false
  artifacts:
    - image: samoz93/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.{ts,js}"
            dest: .
    - image: samoz93/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.{ts,js,tsx,jsx,css,scss}"
            dest: .
    - image: samoz93/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.{ts,js}"
            dest: .
