apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: samoz93
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: samoz93/gallery-api
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: gallery-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: samoz93
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: api
