apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-d
  namespace: samoz93
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: gallery-config
                  key: DB_USER_NAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: gallery-config
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: samoz93
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: db
