apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-samoz
  namespace: samoz93
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: gallery.szoaa.online
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
    - hosts:
        - gallery.szoaa.online
      secretName: letsencrypt-nginx # < cert-manager will store the created certificate in this secret.
